language: node_js
node_js:
- '5.1'
# deploy:
#   provider: s3
#   access_key_id: AKIAISP66RC2ONQAEQMA
#   secret_access_key:
#     secure: jMJkSuZutwvP3zTsbX2IljwOQehBg41RTlR8VcYAQKKK8XI764vXcgmHdKp33UWzsZjEngec3s7z5ZVlwY0pnUIFaPN1vTGRkDwUCrFxW6Zb9ri4Vv3sZR4js+SfHYz/NJ8s27oFyFHtH/U0lS6N6KyHS6CUt+2h7FNC5TdInKDPqdoJmt+CLqpGp21X5SXTWpLkv3UKEz6W3P0fq6sc741XTb8dBaNCbKCFA0eIDO/wFl7XW7QYqAh3Qh5CQlPB765DagOOWGB4g0zJtfbedhDI2Q97XOtBsIPZfWjBvR+RVYfm/NtfXJ5W9woPEsZ6gZi2xKQbvHQ01zCZGNkQ4SFpMZqRjHDjA491yA19VGP9EeSqiZhpnQ8V/dhsx8Bk8ALumUOzA36VLW9XhTWZAzPO27Aqa+VOw2RBXz/hmPeIJUAEleP6SM1Dl8XdC+EgYQEtCAWAepQRgH+DE1efzd5z8988AMyaIot9p8zUDEPYelF9ItsrCZnGN/SBxmycupFxHU/P562WdRMLoFvqSAehV5go7c4tUVaVF39di+/cORagYGiPMdFNa+9KsJE0xGL0h1Dx596zYNMER2ZOC9iHdm7FW9UeIDMJawcJCJXuCaasjwWFCVxKzglDRO2XcBK65gbRjN5gKuypIandF42M7qOw/39KVcWQhnBZHGs=
#   bucket: reacttrader.com
#   skip_cleanup: true
#   local_dir: dist  
#   acl: public_read

provider: heroku
app: trader-client
api_key:
    secure: "B0qYR52SpFJVQd6TXHOn8+VuEVRfMc0oqn5iU/Xc5k5pREVbKg7i2eqIHAUsXFkFVlle9LHRqz2sNjGWWPG/5XYDERcOb9K3hDg4rksuaRCWS7eoUP79s9vPnPxX6xrenEwBBoSd4ivijG+8N/uEsND2qpkRW5MKLxCofLVDjzqVuWRPXj9Oe40QfS96gfaJJ5DAelT6zzTGibbP/bFlZLoxX0jBI1WGrnfo9Se4Sq/Rv7w2Y+3JJrRdrnlsdCX54vHjkM5RdM/IHP6tZyMnmBpGgsRN3W7rcTn3Gl9JVLvwL1bBFMe2BvrO0WTaK98OENzJKTrvDJwAXK3vgtjSidlgZj7LeVFW/QKZur4He1HILVOLD5cavt8jLRX1MM2qRy2bZvlfo3gu+dRYyhB+uFCi9qBYuuo+1jS3jtvHwJALRpxWC/4l0QUDYlWNHlxy5a4ui5UmbShbC+nybd+T5lYwkUP/SSPnMsdR+oTHtPIByib2llLlsYd1co1XgixcsscAJsePyP0VG3eqVngWbjG8fhXLBAGh5bnLSjEPpK673Pu8qk8gPCu32qJc0p+9zI3EZ/Guy3gXO2uKwKCGn73caxey+OfeO6XLwyMtQOgyLwTvjbmeMPC7itAxXaWp2Pc4FuelY97jp/QNSVRXe6r/AMu2+0BoerNSLu03Sto="